spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://129.28.92.132:3306/sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: D:/logs/sell.log
#  level:
#    com.zzf.sell.Test.LoggerTest: debugd

